name: Build Flet APK
on:
  push:
    branches: [ main ] # Se déclenche quand vous envoyez du code sur main
  workflow_dispatch: # Permet de lancer le build manuellement pour tester

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Recommandé pour Android
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # Accélère les builds futurs

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Flet and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build APK
        run: |
          # Création de l'APK
          # --verbose permet de voir les erreurs détaillées si le build échoue
          flet build apk --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-flet-app-release
          path: build/apk/*.apk
          retention-days: 7 # Supprime le fichier après 7 jours pour gagner de la place
